export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY';
export const EMPTY_CART = 'EMPTY_CART';
export const INCREASE_ITEM_QUANTITY = 'INCREASE_ITEM_QUANTITY';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const UPDATE_USER_INFOS = 'UPDATE_USER_INFOS';
